name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - run: pnpm build

      - run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          pnpm -r publish --access public --no-git-checks

      - uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "chore: update docs"
